### ISSUE TITLE
This is Angela's Issue

### ISSUE THREAD

**Issue by AngelaFrench** [18F/hourofcode#126]
yadda yadda

**Comment by AngelaFrench** [comment]
- yadda
- yadda

**Comment by wslack** [comment]
* Yadda
* Yadda
* Yadda

**Comment by wslack** [comment]
Good job! I hope you enjoyed the class and that it was helpful. Feel free to ping here with any further specific questions. Feedback survey will come as well. 

(will close issue for now, but you can still post here)
