### ISSUE TITLE
I am late but this is my issue for class

### ISSUE THREAD

**Issue by joshuagee** [18F/hourofcode#190]
**Testing** and _linking_. 

- [x] I don't really know what a task looks like

**Comment by joshuagee** [comment]
Like that!

**Comment by AminPIC** [comment]
nice!

**Comment by wslack** [comment]
Good job! Note that you wrote linking in italics....not a link.

Thanks for coming!

**Comment by joshuagee** [comment]
Thank you! This was helpful. I was struggling to figure out some things about committing. I've been using issues quite robustly here at the City. Check out this:

https://github.com/CityOfBoston/Forms/issues

**Comment by wslack** [comment]
Oh neat!
