### ISSUE TITLE
This is my issue for Class!

### ISSUE THREAD

**Issue by BrutiAnteneh** [18F/hourofcode#218]
#This is a header

This is some body content.

* This is a bullet
* This is another bullet

**Comment by wslack** [comment]
Good job! Note that you need a space after # to make the header work - try to edit your comment if you'd like.

Feel free to pose more questions about the class here or in the [Federalist repo](https://github.com/18F/federalist/issues/new). (You can click the button below to "reopen" this issue if you want).
