### ISSUE TITLE
This is a new issue

### ISSUE THREAD

**Issue by gigifrias** [18F/hourofcode#223]
# HEADER
Praesent ac massa at ligula laoreet iaculis. Nam commodo suscipit quam. Nulla sit amet est. Praesent metus tellus, elementum eu, semper a, adipiscing nec, purus. Praesent congue erat at massa.

* Issue the first
* Second issue goes here
* The third

**Comment by wslack** [comment]
Good job and thanks for attending! 

Feel free to pose more questions about the class here or in the [Federalist repo](https://github.com/18F/federalist/issues/new). (You can click the button below to "reopen" this issue if you want).
