### ISSUE TITLE
Luis Medina's Issue for Class

### ISSUE THREAD

**Issue by L0uee** [18F/hourofcode#224]
## What Style is applied for H1 or H2?

I want to learn how the Github styles are managed and reconciled

*This is a bullet that I assume carries the same style as my site

1. I want more issues
2. I am done of ieesu

**Comment by wslack** [comment]
Good job and thanks for attending! 

Note that your bullet needs a space after the * to work.

Feel free to pose more questions about the class here or in the [Federalist repo](https://github.com/18F/federalist/issues/new). (You can click the button below to "reopen" this issue if you want).
