### ISSUE TITLE
Is there a helpdesk or listserv for my newb questions?

### ISSUE THREAD

**Issue by bruce-usab** [18F/hourofcode#233]
I thought I was trying something simple, i.e. replace hero.png with the wide banner graphic we use on Twitter.

How do I navigate to the 
\- /assets/uswds/img/
directory?

**Comment by wslack** [comment]
Hi @bruce-usab there's a support e-mail but its only for partners, but this works ok - or e-mailing the inquiries address.

The link I think you want is: https://github.com/bruce-usab/wslack-demo24

Then look for "assets" and click through until you see: https://github.com/bruce-usab/wslack-demo24/blob/master/assets/img/feature-background.jpg

**Comment by bruce-usab** [comment]
Thanks @wslack, but I do not have nearly the same directory structure from using the USWDS template as find in the slack-demo24 (which I think used the “modern” template?

I am not sure how to show what I am seeing.  Should I post a couple screen shots?

**Comment by wslack** [comment]
Sure! I wasn't sure which template you were referring to. Was it this line of code? https://github.com/bruce-usab/uswds-test/blob/master/pages/landing.html#L8

**Comment by wslack** [comment]
If so, the way to address that is to add the new image you want into this repo, then change the line of code above to look at /assets/img/newimage.png instead of where its looking currently. (everything in the /uswds/ folder is loaded into the build container separately)

**Comment by bruce-usab** [comment]
Thanks @wslack, that is getting me much closer.  I cannot find the assets folder.  But I can certainly edit the landing.html page to point to the file I uploaded.

**Comment by wslack** [comment]
Assets folder! https://github.com/bruce-usab/uswds-test/tree/master/assets

**Comment by bruce-usab** [comment]
Sorry, I should have been more clear.
I found _that_ asset folder, and it where I uploaded my graphic.  But the “hero.png” file is not in that directory.  The only file in that directory is “us_seal.png”.

But I will be following your email advice and try the Modern Team Template instead of USWDS.

**Comment by wslack** [comment]
👍 sounds good.

The hero file you couldn't find doesn't actually live in your repo. Instead, the build container loads it in from the USWDS during the build process. Super great if you want to build from your code + another source but not transparent.
