### ISSUE TITLE
Has anyone tried to incorporate a PIA into a repo?

### ISSUE THREAD

**Issue by rspeidel** [18F/hourofcode#241]

**Comment by wslack** [comment]
Hopefully! 🔦 ⚡️ 🔣 👍

**Comment by wslack** [comment]
This is me adding a comment.

**This is in bold**.

**Comment by rspeidel** [comment]
Thanks Will!

Richard Speidel, J.D., CIPP/G
Chief Privacy Officer
General Services Administration
richard.speidel@gsa.gov
(202) 322-8246
