### ISSUE TITLE
Practicing my way around github's issues tab (30 Sep 2023)

### ISSUE THREAD

**Issue by agworkgit** [18F/hourofcode#261]
**My first interaction with github's issues tab as part of my bootcamp in front end development**
_By taking this bootcamp I have committed to life long journey of learning code_
Feel free to give me tips and tricks on my beginner journey or connect with me [here](https://twitter.com/agworksbox) 

Edit! - My name is Alex and I live in London, United Kingdom

**Comment by wslack** [comment]
good job!
