### ISSUE TITLE
My first issue

### ISSUE THREAD

**Issue by c-woolrych** [18F/hourofcode#279]
### My Issues
**Hello World!**
_Hello World_

[Link to world!](https://18f.gsa.gov)

> Terribly excited

`string code = get_string("Enter code: ");` 

1. Two types of people
2. Those who can extrapolate from incomplete data

- work to live
- live to work

- [ ] Complete pre-work
- [ ] Complete bootcamp

Edit:

**Comment by wslack** [comment]
👍
