### ISSUE TITLE
I am having many issues

### ISSUE THREAD

**Issue by ElanaShneyerUSDS** [18F/hourofcode#291]
### This is a very helpful training & a question about Checks

_Thank you @wslack_ 

I am appreciative of the detailed explanations and opportunity to practice.

How are checks set up on the back end and who makes them?

Is this answer correct [link!](https://docs.github.com/en/rest/checks?apiVersion=2022-11-28)

**Comment by wslack** [comment]
:)

You mean the checks in an issue or where?

- [ ] Task list item 1
- [ ] Item 2
