### ISSUE TITLE
New Issue for class

### ISSUE THREAD

**Issue by LeenaCruz** [18F/hourofcode#304]
**Issue Name** 

__This should be in italics!_

**This is bold.** 
[This is a link](https://github.com/18f/hourofcode)

Edit! 

1. List 
2. List 2 

![Github-desktop-logo-symbol svg](https://github.com/18F/hourofcode/assets/16905235/b6cd6c6d-dcc0-48ee-9922-2fff21e2bed5)

**Comment by wslack** [comment]
Good job! Did you mean for the large image?
