### ISSUE TITLE
This is my issue for class

### ISSUE THREAD

**Issue by CHENRY70** [18F/hourofcode#323]
why haven't other companies taken the approach that Arizona Iced Tea has taken, "inflation is just an imaginary things, lets jus keep everything at 99 cents"(I don't know if they are still selling them for 99 cents but if they are I strive to be as helpful as them. thank you for the lecture

**Comment by CHENRY70** [comment]
#####type something
**123**
_squiggly lines_

**Comment by wslack** [comment]
The header markdown there didn't quite work, heads up. Feel free to reopen if you want to try again.
